name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        include:
        - os: ubuntu-lastest
          package-file: tw-econ-*-inux_x86_64.tar.xz
        - os: windows-lastest
          package-file: tw-econ-*-win64.zip
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Pack linux
      if: contains(matrix.os, 'ubuntu')
      run: |
        cd target
        cd debug
        tar cf ${{ matrix.package-file }} tw-econ
        mkdir artifacts
        mv ${{ matrix.package-file }} artifacts
    - name: Pack windows
      if: contains(matrix.os, 'windows')
      run: |
        cd target
        cd debug
        tar cf ${{ matrix.package-file }} tw-econ.exe
        mkdir artifacts
        mv ${{ matrix.package-file }} artifacts
    - name: Upload Artifacts
      uses: actions/upload-artifact@v1
      with:
        name: tw-econ-${{ matrix.os }}
        path: target/debug/artifacts